years: 500 # Number of years to simulate
dt_years: 1 # Time step in years
nx: 200 # Number of grid points in x-direction (x = sin(latitude))
modes: # List of model modes to use. Possible modes are: SeasonalVariation, VariableSeaDepth. Leave empty for default mode.
ctrl_years: # Number of years to run control without forcing. Leave empty to have half the simulation as control.
